### ISSUE TITLE
Crash on starting

### ISSUE THREAD

**Issue by ghtg** [MEMEZNUT999/fluxus-key-bypasser#9]
OS: Windows 10 x64
Python 3.10

Traceback (most recent call last):
  File "main.py", line 93, in <module>
    main()
  File "main.py", line 67, in main
    driver = webdriver.Chrome(options=options)
  File "C:\Users\SASEN1\AppData\Local\Programs\Python\Python38\lib\site-packages\seleniumwire\webdriver.py", line 218, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\SASEN1\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\SASEN1\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 56, in __init__
    super().__init__(
  File "C:\Users\SASEN1\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "C:\Users\SASEN1\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 290, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "C:\Users\SASEN1\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "C:\Users\SASEN1\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Failed to create Chrome process.
Stacktrace:
Backtrace:
        Ordinal0 [0x0084ACD3+2075859]
        Ordinal0 [0x007DEE61+1633889]
        Ordinal0 [0x006DB7BD+571325]
        Ordinal0 [0x006F94C0+693440]
        Ordinal0 [0x006F6BE9+682985]
        Ordinal0 [0x0072DBD3+908243]
        Ordinal0 [0x0072D6AA+906922]
        Ordinal0 [0x00727136+880950]
        Ordinal0 [0x006FFEFD+720637]
        Ordinal0 [0x00700F3F+724799]
        GetHandleVerifier [0x00AFEED2+2769538]
        GetHandleVerifier [0x00AF0D95+2711877]
        GetHandleVerifier [0x008DA03A+521194]
        GetHandleVerifier [0x008D8DA0+516432]
        Ordinal0 [0x007E682C+1665068]
        Ordinal0 [0x007EB128+1683752]
        Ordinal0 [0x007EB215+1683989]
        Ordinal0 [0x007F6484+1729668]
        BaseThreadInitThunk [0x74F8FA29+25]
        RtlGetAppContainerNamedObjectPath [0x76EF7A9E+286]
        RtlGetAppContainerNamedObjectPath [0x76EF7A6E+238]

**Comment by Shiawaseu** [comment]
Hello

Could you please try reinstalling the selenium package and let me know?

Also [this](https://stackoverflow.com/questions/71340051/unknown-error-failed-to-create-chrome-process) might help you

**Comment by Shiawaseu** [comment]
Closed for inactivity.
